The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....2021-02-19 13:54:34.751 UTC [47] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-02-19 13:54:34.756 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-02-19 13:54:34.857 UTC [48] LOG:  database system was shut down at 2021-02-19 13:54:25 UTC
2021-02-19 13:54:36.092 UTC [47] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....2021-02-19 13:54:46.446 UTC [47] LOG:  received fast shutdown request
2021-02-19 13:54:46.648 UTC [47] LOG:  aborting any active transactions
2021-02-19 13:54:47.264 UTC [47] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
2021-02-19 13:54:47.266 UTC [49] LOG:  shutting down
.2021-02-19 13:54:47.959 UTC [47] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2021-02-19 13:54:48.592 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-02-19 13:54:49.115 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-02-19 13:54:49.117 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-02-19 13:54:49.172 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-02-19 13:54:49.296 UTC [65] LOG:  database system was shut down at 2021-02-19 13:54:47 UTC
2021-02-19 13:54:50.444 UTC [1] LOG:  database system is ready to accept connections
2021-02-19 13:55:53.666 UTC [73] ERROR:  relation "nodes" does not exist at character 115
2021-02-19 13:55:53.666 UTC [73] STATEMENT:  SELECT "node"."id", "node"."health", "node"."checksum", "node"."responsibility_center", "node"."inbound_url" FROM "nodes" AS "node"
2021-02-19 13:56:00.057 UTC [73] ERROR:  relation "nodes" does not exist at character 115
2021-02-19 13:56:00.057 UTC [73] STATEMENT:  SELECT "node"."id", "node"."health", "node"."checksum", "node"."responsibility_center", "node"."inbound_url" FROM "nodes" AS "node"
2021-02-19 13:56:06.514 UTC [73] ERROR:  relation "nodes" does not exist at character 115
2021-02-19 13:56:06.514 UTC [73] STATEMENT:  SELECT "node"."id", "node"."health", "node"."checksum", "node"."responsibility_center", "node"."inbound_url" FROM "nodes" AS "node"
2021-02-19 13:56:13.604 UTC [73] ERROR:  relation "nodes" does not exist at character 115
2021-02-19 13:56:13.604 UTC [73] STATEMENT:  SELECT "node"."id", "node"."health", "node"."checksum", "node"."responsibility_center", "node"."inbound_url" FROM "nodes" AS "node"
